"""aligned_foundation_schema

Revision ID: 271fb424ed39
Revises: 
Create Date: 2026-09-19 12:52:08.490153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271fb424ed39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=32), nullable=False),
    sa.Column('boundary_geometry', sa.JSON(), nullable=True),
    sa.Column('crop_profile', sa.JSON(), nullable=True),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_farm_id'), 'audit_events', ['farm_id'], unique=False)
    op.create_index('ix_audit_events_farm_timestamp', 'audit_events', ['farm_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('farm_memberships',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_memberships_farm_id'), 'farm_memberships', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_memberships_id'), 'farm_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_farm_memberships_user_id'), 'farm_memberships', ['user_id'], unique=False)
    op.create_table('zones',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=32), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('crop', sa.String(length=128), nullable=True),
    sa.Column('crop_stage', sa.String(length=64), nullable=True),
    sa.Column('soil_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_farm_id'), 'zones', ['farm_id'], unique=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('calibration', sa.JSON(), nullable=True),
    sa.Column('credential_reference', sa.String(length=128), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_credential_reference'), 'devices', ['credential_reference'], unique=True)
    op.create_index(op.f('ix_devices_farm_id'), 'devices', ['farm_id'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_zone_id'), 'devices', ['zone_id'], unique=False)
    op.create_table('external_observations',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('freshness', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_external_obs_farm_type', 'external_observations', ['farm_id', 'type'], unique=False)
    op.create_index('ix_external_obs_validity', 'external_observations', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_external_observations_farm_id'), 'external_observations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_external_observations_id'), 'external_observations', ['id'], unique=False)
    op.create_index(op.f('ix_external_observations_type'), 'external_observations', ['type'], unique=False)
    op.create_index(op.f('ix_external_observations_zone_id'), 'external_observations', ['zone_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('risk_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_farm_id'), 'risk_assessments', ['farm_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_type'), 'risk_assessments', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risk_assessments_severity'), 'risk_assessments', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_assessments_status'), 'risk_assessments', ['status'], unique=False)
    op.create_index(op.f('ix_risk_assessments_zone_id'), 'risk_assessments', ['zone_id'], unique=False)
    op.create_index('ix_risk_farm_created', 'risk_assessments', ['farm_id', 'created_at'], unique=False)
    op.create_index('ix_risk_status_severity', 'risk_assessments', ['status', 'severity'], unique=False)
    op.create_table('action_plans',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('risk_id', sa.String(length=36), nullable=True),
    sa.Column('source_risk_ids', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('earliest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('safety_flags', sa.JSON(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('policy_decision', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_plans_farm_created', 'action_plans', ['farm_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_action_plans_farm_id'), 'action_plans', ['farm_id'], unique=False)
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_index('ix_action_plans_policy_decision', 'action_plans', ['policy_decision'], unique=False)
    op.create_index(op.f('ix_action_plans_risk_id'), 'action_plans', ['risk_id'], unique=False)
    op.create_index(op.f('ix_action_plans_zone_id'), 'action_plans', ['zone_id'], unique=False)
    op.create_table('alerts',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('risk_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_dedupe_key', 'alerts', ['dedupe_key'], unique=False)
    op.create_index('ix_alerts_farm_created', 'alerts', ['farm_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_farm_id'), 'alerts', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_risk_id'), 'alerts', ['risk_id'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('sensor_events',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'sequence', name='uq_device_sequence')
    )
    op.create_index('ix_sensor_events_device_event_at', 'sensor_events', ['device_id', 'event_at'], unique=False)
    op.create_index(op.f('ix_sensor_events_device_id'), 'sensor_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_events_event_at'), 'sensor_events', ['event_at'], unique=False)
    op.create_index('ix_sensor_events_farm_event_at', 'sensor_events', ['farm_id', 'event_at'], unique=False)
    op.create_index(op.f('ix_sensor_events_farm_id'), 'sensor_events', ['farm_id'], unique=False)
    op.create_index(op.f('ix_sensor_events_id'), 'sensor_events', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_events_metric'), 'sensor_events', ['metric'], unique=False)
    op.create_index('ix_sensor_events_zone_event_at', 'sensor_events', ['zone_id', 'event_at'], unique=False)
    op.create_index(op.f('ix_sensor_events_zone_id'), 'sensor_events', ['zone_id'], unique=False)
    op.create_table('escalations',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('risk_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_expert_id', sa.String(length=64), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('review_outcome', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_farm_id'), 'escalations', ['farm_id'], unique=False)
    op.create_index('ix_escalations_farm_status', 'escalations', ['farm_id', 'status'], unique=False)
    op.create_index(op.f('ix_escalations_id'), 'escalations', ['id'], unique=False)
    op.create_index(op.f('ix_escalations_plan_id'), 'escalations', ['plan_id'], unique=False)
    op.create_index(op.f('ix_escalations_risk_id'), 'escalations', ['risk_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_escalations_zone_id'), 'escalations', ['zone_id'], unique=False)
    op.create_table('tasks',
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_until'), 'tasks', ['due_until'], unique=False)
    op.create_index(op.f('ix_tasks_farm_id'), 'tasks', ['farm_id'], unique=False)
    op.create_index('ix_tasks_farm_status', 'tasks', ['farm_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_plan_id'), 'tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_status_due_window', 'tasks', ['status', 'due_from', 'due_until'], unique=False)
    op.create_index(op.f('ix_tasks_zone_id'), 'tasks', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_zone_id'), table_name='tasks')
    op.drop_index('ix_tasks_status_due_window', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_plan_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index('ix_tasks_farm_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_farm_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_until'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_escalations_zone_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_risk_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_plan_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_id'), table_name='escalations')
    op.drop_index('ix_escalations_farm_status', table_name='escalations')
    op.drop_index(op.f('ix_escalations_farm_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_sensor_events_zone_id'), table_name='sensor_events')
    op.drop_index('ix_sensor_events_zone_event_at', table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_metric'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_id'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_farm_id'), table_name='sensor_events')
    op.drop_index('ix_sensor_events_farm_event_at', table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_event_at'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_device_id'), table_name='sensor_events')
    op.drop_index('ix_sensor_events_device_event_at', table_name='sensor_events')
    op.drop_table('sensor_events')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_farm_id'), table_name='alerts')
    op.drop_index('ix_alerts_farm_created', table_name='alerts')
    op.drop_index('ix_alerts_dedupe_key', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_action_plans_zone_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_risk_id'), table_name='action_plans')
    op.drop_index('ix_action_plans_policy_decision', table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_farm_id'), table_name='action_plans')
    op.drop_index('ix_action_plans_farm_created', table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index('ix_risk_status_severity', table_name='risk_assessments')
    op.drop_index('ix_risk_farm_created', table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_zone_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_status'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_severity'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_type'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_farm_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_external_observations_zone_id'), table_name='external_observations')
    op.drop_index(op.f('ix_external_observations_type'), table_name='external_observations')
    op.drop_index(op.f('ix_external_observations_id'), table_name='external_observations')
    op.drop_index(op.f('ix_external_observations_farm_id'), table_name='external_observations')
    op.drop_index('ix_external_obs_validity', table_name='external_observations')
    op.drop_index('ix_external_obs_farm_type', table_name='external_observations')
    op.drop_table('external_observations')
    op.drop_index(op.f('ix_devices_zone_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_farm_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_credential_reference'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_farm_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_farm_memberships_user_id'), table_name='farm_memberships')
    op.drop_index(op.f('ix_farm_memberships_id'), table_name='farm_memberships')
    op.drop_index(op.f('ix_farm_memberships_farm_id'), table_name='farm_memberships')
    op.drop_table('farm_memberships')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_farm_timestamp', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_farm_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
